[build]
  base = "dirtydiapersstudio"
  command = "npm run build"
  publish = ".netlify/build"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NETLIFY_NEXT_PLUGIN_FORCE = "true"
